project:
  type: book
  output-dir: docs

book:
  title: "quarto_book_sandbox"
  author: "Joe Post"
  date: "19/01/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - week1.qmd
    - week2.qmd
    - week3.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo  #for list of themes, see: https://bootswatch.com/default/
  pdf:
    documentclass: scrreprt

editor: visual

