project:
  type: book
  output-dir: docs

book:
  title: "CASA0023 Weekly Learning Diary"
  author: "Joe Post"
  date: "19/01/2023"
  chapters:
    - index.qmd
    - week1.qmd
    - week2.qmd
    - week3.qmd
    - week4.qmd
    - week5.qmd
    - week6.qmd
    - week7.qmd
    - week8.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo  #for list of themes, see: https://bootswatch.com/default/
  pdf:
    documentclass: scrreprt

editor: visual

